### DISCUSSION TITLE
How can Langflow be configured for high availability (HA)?

### DISCUSSION THREAD

**Discussion by lianlian1212** [langflow-ai/langflow#10506] [General]
How can Langflow be configured for high availability (HA)?

Version 1.4.2 still throws an error when starting 2 pods

Error Building Component
Network error. Please check the connection to the server.

**Comment by dosubot** [comment]
To configure Langflow version 1.4.2 for high availability without encountering a network error when starting two pods, ensure both instances are set up to share the same PostgreSQL database. Here's a step-by-step guide:

1. **Configure the `.env` file** with the necessary PostgreSQL database credentials and Langflow settings:
   ```text
   POSTGRES_USER=langflow
   POSTGRES_PASSWORD=your_secure_password
   POSTGRES_DB=langflow
   POSTGRES_HOST=postgres
   POSTGRES_PORT=5432
   LANGFLOW_CONFIG_DIR=app/langflow
   LANGFLOW_PORT_1=7860
   LANGFLOW_PORT_2=7861
   LANGFLOW_HOST=0.0.0.0
   ```

2. **Use the following `docker-compose.yml` configuration** to deploy two Langflow instances (`langflow-1` and `langflow-2`) that share the same PostgreSQL database:
   ```yaml
   services:
     postgres:
       image: postgres:16
       environment:
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_DB=${POSTGRES_DB}
       ports:
         - "${POSTGRES_PORT}:5432"
       volumes:
         - langflow-postgres:/var/lib/postgresql/data

     langflow-1:
       image: langflowai/langflow:latest
       pull_policy: always
       ports:
         - "${LANGFLOW_PORT_1}:7860"
       depends_on:
         - postgres
       environment:
         - LANGFLOW_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
         - LANGFLOW_CONFIG_DIR=${LANGFLOW_CONFIG_DIR}
         - LANGFLOW_HOST=${LANGFLOW_HOST}
         - PORT=7860
       volumes:
         - langflow-data-1:/app/langflow

     langflow-2:
       image: langflowai/langflow:latest
       pull_policy: always
       ports:
         - "${LANGFLOW_PORT_2}:7860"
       depends_on:
         - postgres
       environment:
         - LANGFLOW_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
         - LANGFLOW_CONFIG_DIR=${LANGFLOW_CONFIG_DIR}
         - LANGFLOW_HOST=${LANGFLOW_HOST}
         - PORT=7860
       volumes:
         - langflow-data-2:/app/langflow

   volumes:
     langflow-postgres:
     langflow-data-1:
     langflow-data-2:
   ```

This setup ensures both Langflow instances are connected to the same database, allowing for high availability. Verify that the network settings and ports are correctly configured to avoid network errors <sup>[[1]](https://github.com/langflow-ai/langflow/blob/main/docs/docs/Configuration/configuration-custom-database.md)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/5753733a-aa43-48c2-aa08-ca7ab0ef1d35?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/5753733a-aa43-48c2-aa08-ca7ab0ef1d35?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/5753733a-aa43-48c2-aa08-ca7ab0ef1d35?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/5753733a-aa43-48c2-aa08-ca7ab0ef1d35?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/5753733a-aa43-48c2-aa08-ca7ab0ef1d35?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/5753733a-aa43-48c2-aa08-ca7ab0ef1d35?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/5753733a-aa43-48c2-aa08-ca7ab0ef1d35?feedback_type=other)</sup>
