### DISCUSSION TITLE
Proposal: Yaml-based abstraction of business logic, excluding node internals and formatting/layout

### DISCUSSION THREAD

**Discussion by aaronsteers** [langflow-ai/langflow#202] [Ideas]
I'd like to be able to commit the output of `langflow` to a repo in a human-readable fashion. And I'd like to then be able to modify the yaml 

The export to json today essentially has a superset of what we'd want to manage in git.

Some cosmetic info, such as node x and y locations may be lost in the translation. I can think of three options for how to deal with cosmetic layout info:

- Option 1: layout info is not saved. 
- Option 2: layout info is saved to a separate file. 
- Option 3: layout info is optionally saved to yaml, or not, based on user preference.

In all of these options, if there is some missing node layout info, like missing x and y coords, then the library may put them in an awkward location, or else do its best to position them logically in a decent position relative to the nodes it connects to.

While it would be a significant amount of effort to decouple the business logic from the node/graph layout info, this extends the core value proposition of LangFlow being an accessible means of authoring workflows, and extends that value-prop to also have copy-pasteable and having the ability for users to  yaml accessibility.

**Comment by ogabrielluiz** [comment]
I completely agree with you. 
There are many attributes that are passed back to the backend that are used only in the frontend.

Your suggestions are valid and we have thought about some of them before.

To me, the approach we should take: don't save the layout info and have a simple logic to auto-layout (I think react-flow has that functionality) when loading them back.

Regarding YAML, It would be possible to translate the JSON into YAML but that would require a stable API for the templates which we are constantly adapting as we see more functions being implemented and we define better patterns.

The YAML could be something like:
```yaml
Nodes:
	node_id1
		- LLMChain:
			- llm: OpenAI
			- prompt: PromptTemplate
	node_id2
		- OpenAI:
			- model_name: text-davinci-003
			etc.
```

But then we'd still have to save the graph info (nodes and edges) somewhere which would be kind of weird. We can brainstorm a bit more, I think.

Thanks for bringing this up.

**Reply by aaronsteers** [reply]
@ogabrielluiz - thanks for sharing your thoughts. I actually created a mock-up of what this might look like, and the cleanest I could get to was something like the following:

```yml
documents:
- id: state-of-the-union-text-file
  type: TextLoader # literal class name
  config: ... # constructor args go here
# ...
llms:
- id: OpenAI
  type: OpenAI
  # ...
splitters:
- id: newline-text-splitter
  type: TextSplitter
  config:
    delimiter: "\n"
    # ...
vectorstores:
- id: MyChomaDB # unique key
  type: Chroma # class name
  config:
    # constructor args go here (may be handled directly or passed as kwargs)
    persist_directory: /path/to/db
  documents:
  - document_id: state-of-the-union-text-file
    splitter_id: newline-text-splitter
    collection_name: "Text documents"
    embeddings:
      type: OpenAIEmbeddings
```

So, this is of course just one of many possible layout and scheme options, but I found it made sense to (where appropriate) declare the class name explicitly and allow for arbitrary constructor args under a shared header ("config" in the above).

Whether to model them as nodes with generic inputs and outputs, versus modeling them as entities of a specific domain (documents, LLMs, etc.) is another question with probably strengths on both sides. In the above mock up, the document is one of potentially many that could be loaded to the vectorstore, but rather than modeling as generic inputs, they are modeled according to an expected contract... such as (1) document_id is required, (2) splitter_id is optional, and (3) embeddings can be defined inline as a property of the specific import process. 

Modeling these as generic nodes can also work, but the above is tuned to (hopefully/eventually) be able to provide JSON Schema validation assistance and autocomplete during text editing. Richer types in theory could build into the schema layouts certain business logic expectations and validation rules.

Curious what you think of this...

**Reply by ogabrielluiz** [reply]
The Ids are the problem in this case. If I have two Tool nodes they need to be unique in some way.


I have this [example flow](https://gist.github.com/ogabrielluiz/19f7db62b021a8133f5bfebe22808e62) that uses the PythonFunction node to generate an image. 
I ran the following code:
```python
import json
import yaml
with open('Imageflow.json', 'r') as f:
    data = json.load(f)

def template_to_dict(template):
    result = {}
    for key in template.keys():
       if key == '_type':
            result[key] = template[key]
            continue
       templ_dict = template[key]
       result[key] = templ_dict.get('value', None)
    return result

def nodes_to_list(nodes):
    result = []
    for node in nodes:
        result.append(node_to_dict(node))
    return result

def edges_to_list(edges):
    result = []
    for edge in edges:
        result.append({'source': edge['source'], 'target': edge['target']})
    return result

def node_to_dict(node):
    result = {}
    result['id'] = node['id']
    result['template'] = template_to_dict(node['data']['node']['template'])
    return result



# data json has a data key, which with edges and nodes keys
nodes = data['data']['nodes']
edges = data['data']['edges']

nodes_list = nodes_to_list(nodes)
edges_list = edges_to_list(edges)

workflow_data = {
    'nodes': nodes_list,
    'edges': edges_list
}

yaml_data = yaml.dump(workflow_data, sort_keys=False)
with open('Imageflow.yaml', 'w') as f:
    yaml.dump(workflow_data, f)
```
The result is this:

```yaml
edges:
  - source: dndnode_7
    target: dndnode_1
  - source: dndnode_1
    target: dndnode_3
  - source: dndnode_4
    target: dndnode_3
  - source: dndnode_8
    target: dndnode_3
nodes:
  - id: dndnode_1
    template:
      _type: Tool
      description: Use this to pass a prompt and generate an image with DALL-E2
      func: null
      name: ImageGenerator
      return_direct: true
  - id: dndnode_3
    template:
      _type: initailize_agent
      agent: zero-shot-react-description
      llm: null
      memory: null
      tools: null
  - id: dndnode_4
    template:
      _type: OpenAI
      batch_size: 20
      best_of: 1
      cache: null
      client: null
      frequency_penalty: 0
      logit_bias: null
      max_retries: 6
      max_tokens: 256
      model_kwargs: null
      model_name: text-davinci-003
      n: 1
      openai_api_key: sk-
      presence_penalty: 0
      request_timeout: null
      streaming: false
      temperature: "0.0"
      top_p: 1
      verbose: null
  - id: dndnode_7
    template:
      _type: python_function
      code:
        "import openai\nfrom langflow import cache_manager\nimport io\nimport base64\n\
        import os\nfrom PIL import Image\n\ndef create_image(prompt: str) -> str:\n\
        \    openai.api_key = os.getenv(\"OPENAI_API_KEY\")\n\n    response = openai.Image.create(\n\
        \        prompt=prompt,\n        n=1,\n        size=\"256x256\",\n        response_format=\"\
        b64_json\",\n    )\n    # load the image\n    for image_dict in response[\"\
        data\"]:\n        image_data = base64.b64decode(image_dict[\"b64_json\"])\n\
        \        # Cache image in LangFlow\n        cache_manager.add_image(\"webinar\"\
        , Image.open(io.BytesIO(image_data)))\n        # save the image to disk\n  \
        \      with open(\"image.png\", \"wb\") as f:\n            f.write(image_data)\n\
        \        \n\n    return \"Image generated!\""
  - id: dndnode_8
    template:
      _type: ConversationBufferMemory
      ai_prefix: AI
      chat_memory: null
      human_prefix: Human
      input_key: null
      memory_key: history
      output_key: null
      return_messages: null
```

I  think it is a pretty good result. The frontend would have to process the imported file differently probably here:
https://github.com/logspace-ai/langflow/blob/69c7bbb0a9cf8764e404899b16ad37e22de606a6/src/frontend/src/contexts/tabsContext.tsx#L139

It is a lot cleaner with a lot less data being passed around.

What do you think of this approach?

We got to keep in mind that we have to rebuild the graph.
