### DISCUSSION TITLE
asynio in langflow==0.6.19

### DISCUSSION THREAD

**Discussion by SVyusti** [langflow-ai/langflow#2907] [Q&A]
@dosu getting error ValueError: Can't patch loop of type <class 'uvloop.Loop'> in langflow in docker container but not in local

**Comment by dosubot** [comment]
To resolve the `ValueError: Can't patch loop of type <class 'uvloop.Loop'>` issue with `langflow==0.6.19` when running it in a Docker container, you need to specify the event loop policy to use the default asyncio loop instead of uvloop. You can do this by setting the `UVLOOP_NO_PATCH` environment variable to `1` before running your application.

Here is the modified `docker/container-cmd-cdk.sh` script:

```sh
export LANGFLOW_DATABASE_URL="mysql+pymysql://${username}:${password}@${host}:3306/${dbname}"
export UVLOOP_NO_PATCH=1
# echo $LANGFLOW_DATABASE_URL
uvicorn --factory langflow.main:create_app --host 0.0.0.0 --port 7860 --reload --log-level debug --loop asyncio

# python -m langflow run --host 0.0.0.0 --port 7860
```

This should prevent uvloop from being used and avoid the `ValueError` <sup>[[1]](https://github.com/langflow-ai/langflow/blob/dev/docker/container-cmd-cdk.sh)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Reply by SVyusti** [reply]
no command type --loop exists
command in docker file:
CMD ["/bin/sh", "-c", ". ${PYTHON_VIRTUAL_ENV_FOLDER}/bin/activate && export NLTK_DATA=${PYTHON_VIRTUAL_ENV_FOLDER}/nltk_data && python -m langflow run --host 0.0.0.0 --port 7860"]

**Reply by dosubot** [reply]
To resolve the `ValueError: Can't patch loop of type <class 'uvloop.Loop'>` issue with `langflow==0.6.19` in a Docker container, you should remove the `--loop asyncio` option from the `uvicorn` command, as it is not a valid option for `uvicorn`.

Here is the corrected command:

```sh
export LANGFLOW_DATABASE_URL="mysql+pymysql://${username}:${password}@${host}:3306/${dbname}"
export UVLOOP_NO_PATCH=1
# echo $LANGFLOW_DATABASE_URL
uvicorn --factory langflow.main:create_app --host 0.0.0.0 --port 7860 --reload --log-level debug
```

Additionally, you should update your `docker-compose.yml` file to remove the `--loop asyncio` option from the `command` section for the `backend` service:

```yml
version: "3"
networks:
  langflow:

services:
  backend:
    build:
      context: ./
      dockerfile: ./dev.Dockerfile
    env_file:
      - .env
    ports:
      - "7860:7860"
    volumes:
      - ./:/app
    command: bash -c "uvicorn --factory langflow.main:create_app --host 0.0.0.0 --port 7860 --reload --log-level debug"
    networks:
      - langflow
  frontend:
    build:
      context: ./src/frontend
      dockerfile: ./cdk.Dockerfile
      args:
        - BACKEND_URL=http://backend:7860
    depends_on:
      - backend
    environment:
      - VITE_PROXY_TARGET=http://backend:7860
    ports:
      - "8080:3000"
    volumes:
      - ./src/frontend/public:/home/node/app/public
      - ./src/frontend/src:/home/node/app/src
      - ./src/frontend/package.json:/home/node/app/package.json
    restart: on-failure
    networks:
      - langflow
```

Finally, update your `dev.Dockerfile` to remove the `--loop asyncio` option from the `CMD` instruction:

```Dockerfile
FROM langflowai/backend_build as backend_build

FROM python:3.10-slim
WORKDIR /app

RUN apt-get update && apt-get install git -y

COPY --from=backend_build /app/dist/*.whl /app/
RUN pip install langflow-*.whl
RUN rm *.whl

EXPOSE 80

CMD ["uvicorn", "--factory", "langflow.main:create_app", "--host", "0.0.0.0", "--port", "7860", "--reload", "--log-level", "debug"]
```

This should resolve the issue by not specifying an invalid loop option <sup>[[1]](https://github.com/langflow-ai/langflow/blob/dev/docker/container-cmd-cdk.sh)</sup><sup>[[2]](https://github.com/langflow-ai/langflow/blob/dev/docker/cdk-docker-compose.yml)</sup><sup>[[3]](https://github.com/langflow-ai/langflow/blob/dev/docker/dev.Dockerfile)</sup><sup>[[4]](https://github.com/logspace-ai/langflow/blob/dev/src/backend/Dockerfile)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Reply by SVyusti** [reply]
I want to run a workflow in langflow iteratively, is it possible? @dosu

**Reply by dosubot** [reply]
Yes, it is possible to run a workflow iteratively in LangFlow. You can achieve this by setting up a loop within your workflow logic. Here is a basic example of how you can set up a Docker container for LangFlow and run a workflow iteratively:

1. **Clone the LangFlow repository:**

    ```sh
    git clone https://github.com/langflow-ai/langflow.git
    ```

2. **Navigate to the `docker_example` directory:**

    ```sh
    cd langflow/docker_example
    ```

3. **Modify the Docker Compose file to use the specific version `langflow==0.6.19`:**

    ```yaml
    version: '3.8'

    services:
      langflow:
        image: langflowai/langflow:0.6.19
        ports:
          - "7860:7860"
        environment:
          - LANGFLOW_DATABASE_URL=postgresql://postgres:password@postgres:5432/langflow
          - LANGFLOW_CONFIG_DIR=/var/lib/langflow
        volumes:
          - langflow-data:/var/lib/langflow
        depends_on:
          - postgres

      postgres:
        image: postgres:16
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
          - POSTGRES_DB=langflow
        volumes:
          - langflow-postgres:/var/lib/postgresql/data

    volumes:
      langflow-data:
      langflow-postgres:
    ```

4. **Run the Docker Compose file:**

    ```sh
    docker compose up
    ```

5. **Access LangFlow at [http://localhost:7860/](http://localhost:7860/).**

6. **Implement iterative workflow logic within your LangFlow application:**

    You can create a Python script or modify your existing workflow to include a loop. Here is a simple example of a Python script that runs a workflow iteratively:

    ```python
    from langflow import LangFlow

    def run_workflow():
        # Initialize LangFlow
        lf = LangFlow()

        # Define your workflow logic here
        for i in range 10):  # Example loop running 10 iterations
            print(f"Running iteration {i+1}")
            # Add your workflow steps here
            # lf.step1()
            # lf.step2()
            # ...

    if __name__ == "__main__":
        run_workflow()
    ```

By following these steps, you can set up LangFlow in a Docker container and run your workflows iteratively <sup>[[1]](https://github.com/logspace-ai/langflow/blob/dev/docker_example/README.md)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
