### DISCUSSION TITLE
Connection Error When Running Langflow with Docker via python api

### DISCUSSION THREAD

**Discussion by MoofonLi** [langflow-ai/langflow#3238] [Q&A] [answered]
Hi,
I'm facing an issue with calling the Langflow API from a Python script when running Langflow as part of a Docker Compose setup. The Langflow service itself appears to be running fine, but API calls from Python are failing with the following error:
```
An error occurred while calling the API: HTTPConnectionPool(host='localhost', port=7860): Max retries exceeded with url: /api/v1/run/69f150f2-8269-4f85-8b31-c8ae596c6bec (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb8411a5ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
And this is my function for running langflow:
```
def run_flow(message: str,
             endpoint: str,
             output_type: str = "chat",
             input_type: str = "chat",
             tweaks: Optional[dict] = None,
             api_key: Optional[str] = None,
             session_id: Optional[str] = None) -> dict:
    
    api_url = f"{BASE_API_URL}/api/v1/run/{endpoint}"

    payload = {
        "input_value": message,
        "output_type": output_type,
        "input_type": input_type,
        "session_id": session_id,
    }
    headers = None
    if tweaks:
        payload["tweaks"] = tweaks
    if api_key:
        headers = {"x-api-key": api_key}
    
    response = requests.post(api_url, json=payload, headers=headers)
    return response.json()
```

**Comment by dosubot** [comment]
To resolve the connection error when calling the Langflow API from a Python script in a Docker Compose setup, ensure that your Docker Compose file is correctly configured to expose the necessary ports and that your Python script is targeting the correct host and port.

Here is an example of how you can set up your `docker-compose.yml` file:

```yaml
version: '3.8'

services:
  langflow:
    image: langflowai/langflow:1.0-alpha
    ports:
      - "7860:7860"
    command: ["uvicorn", "--host", "0.0.0.0", "--port", "7860", "--factory", "langflow.main:create_app"]
```

In your Python script, you should then target `http://localhost:7860` or `http://<docker_host_ip>:7860` if you are running the script outside the Docker network. Here is an example of a Python script making a request to the Langflow API:

```python
import requests

BASE_API_URL = "http://localhost:7860"

def run_flow(message: str,
             endpoint: str,
             output_type: str = "chat",
             input_type: str = "chat",
             tweaks: Optional[dict] = None,
             api_key: Optional[str] = None,
             session_id: Optional[str] = None) -> dict:
    
    api_url = f"{BASE_API_URL}/api/v1/run/{endpoint}"

    payload = {
        "input_value": message,
        "output_type": output_type,
        "input_type": input_type,
        "session_id": session_id,
    }
    headers = None
    if tweaks:
        payload["tweaks"] = tweaks
    if api_key:
        headers = {"x-api-key": api_key}
    
    response = requests.post(api_url, json=payload, headers=headers)
    return response.json()
```

Make sure to replace `your_api_endpoint` with the actual endpoint you are trying to access <sup>[[1]](https://github.com/logspace-ai/langflow/blob/dev/docker_example/Dockerfile)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Reply by MoofonLi** [reply]
@dosu
This is my docker-compose.yml file:
```
  langflow:
    image: langflowai/langflow:latest
    user: root
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      - LANGFLOW_CONFIG_DIR=/var/lib/langflow
    volumes:
      - langflow-data:/var/lib/langflow
    depends_on:
      - postgres
```
Do I need to change anything?
