### DISCUSSION TITLE
How to set up a workflow that runs automatically every day?

### DISCUSSION THREAD

**Discussion by SiuLeeBoss** [langflow-ai/langflow#3811] [Q&A]
I want to set up a workflow that can run automatically every day. Where can I start?

**Comment by dosubot** [comment]
@SiuLeeBoss Hello there! I'm a bot here to help you with any questions or issues you may have. Feel free to ask me anything, and I'll do my best to assist you while waiting for a human maintainer.


To set up a workflow that runs automatically every day, you need to modify the `schedule` section of your GitHub Actions workflow file. Specifically, you should change the cron expression to run daily. Here is an example configuration:

```yml
name: Integration tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "(Optional) Branch to checkout"
        required: false
        type: string
  schedule:
    - cron: "0 0 * * *" # Run every day

env:
  POETRY_VERSION: "1.8.2"

jobs:
  test-integration:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1 # Currently, we can only run at a time for collection-per-db-constraints
      matrix:
        python-version:
          - "3.12"
          - "3.11"
          - "3.10"
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ASTRA_DB_API_ENDPOINT: ${{ secrets.ASTRA_DB_API_ENDPOINT }}
      ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch || github.ref }}
      - name: Set up Python ${{ matrix.python-version }} + Poetry ${{ env.POETRY_VERSION }}
        uses: "./.github/actions/poetry_caching"
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: ${{ env.POETRY_VERSION }}
          cache-key: ${{ runner.os }}-poetry-${{ env.POETRY_VERSION }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install Python dependencies
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry install
      - name: Run integration tests with api keys
        timeout-minutes: 20
        run: |
          make integration_tests_api_keys
```

This configuration will trigger the workflow to run every day at midnight (UTC) <sup>[[1]](https://github.com/langflow-ai/langflow/blob/main/.github/workflows/scheduled_integration_test.yml)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
