### DISCUSSION TITLE
How to save project into k8s

### DISCUSSION THREAD

**Discussion by exilehanharr** [langflow-ai/langflow#5964] [Q&A]
Hi @ALL,

I've deployed langflow to k8s and after deploying a new version of `backend` my created projects delete. How can I save there for next new deployments?

**Comment by dosubot** [comment]
Hey @exilehanharr! 👋 I'm here to help you with that. I'm a bot that can assist you with bug fixes, answer questions, and guide you to become a contributor. Let's tackle this together!


To ensure your Langflow projects persist across deployments in a Kubernetes environment, you can configure Langflow to use an external storage solution. Here are some steps you can take:

1. **Use Persistent Volumes**: Configure Kubernetes Persistent Volumes (PVs) and Persistent Volume Claims (PVCs) to store your project data. This will ensure that your data is not lost when the pods are redeployed.

2. **External Database**: Consider using an external database like PostgreSQL for storing project data. Langflow supports using an external PostgreSQL database, which can be configured in the `values.yaml` file of the Helm chart. This setup allows you to leverage persistent storage and ensure data durability and scalability. You can find more details in the [Langflow Helm Charts repository](https://github.com/langflow-ai/langflow-helm-charts).

3. **Environment Variables**: Ensure that your environment variables and configurations are set up correctly to point to the external storage solution. This can be done using Kubernetes ConfigMaps and Secrets.

By following these steps, you can maintain your project data across deployments in a Kubernetes environment.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/11eea3d0-4abe-4fba-8e35-13cfc206a7c4?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/11eea3d0-4abe-4fba-8e35-13cfc206a7c4?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/11eea3d0-4abe-4fba-8e35-13cfc206a7c4?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/11eea3d0-4abe-4fba-8e35-13cfc206a7c4?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/11eea3d0-4abe-4fba-8e35-13cfc206a7c4?feedback_type=hallucination) | [Other](https://app.dosu.dev/response-feedback/11eea3d0-4abe-4fba-8e35-13cfc206a7c4?feedback_type=other)</sup>

**Reply by exilehanharr** [reply]
@dosu Could you please share an example? I use PostgreSQL

**Reply by dosubot** [reply]
To configure Langflow to use an external PostgreSQL database for persistent storage in Kubernetes, follow these steps:

1. **Create a Kubernetes Secret for PostgreSQL credentials:**

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  username: <base64-encoded-username>
  password: <base64-encoded-password>
```

2. **Create a ConfigMap for Langflow environment variables:**

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: langflow-config
data:
  LANGFLOW_DATABASE_URL: "postgresql://user:password@postgres-service:5432/langflow"
```

3. **Deploy PostgreSQL as a Deployment:**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_DB
          value: langflow
        ports:
        - containerPort: 5432
```

4. **Deploy Langflow using Helm with external PostgreSQL configuration:**

First, add the Langflow Helm repository and update it:

```shell
helm repo add langflow https://langflow-ai.github.io/langflow-helm-charts
helm repo update
```

Then, create a `values.yaml` file to configure the external PostgreSQL database:

```yaml
langflow:
  backend:
    externalDatabase:
      enabled: true
      driver:
        value: "postgresql"
      host:
        value: "postgres-service"
      port:
        value: "5432"
      database:
        value: "langflow"
      user:
        value: "user"
      password:
        valueFrom:
          secretKeyRef:
            key: "password"
            name: "postgres-secret"
    sqlite:
      enabled: false
```

Finally, install Langflow with the Helm chart:

```shell
helm install langflow-ide langflow/langflow-ide -n langflow --create-namespace -f values.yaml
```

5. **Create a Service for PostgreSQL:**

```yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
```

This setup will configure Langflow to use an external PostgreSQL database in a Kubernetes environment. Make sure to replace `<base64-encoded-username>` and `<base64-encoded-password>` with the base64-encoded values of your PostgreSQL username and password <sup>[[1]](https://github.com/langflow-ai/langflow/blob/main/docs/docs/Configuration/configuration-custom-database.md)</sup><sup>[[2]](https://github.com/langflow-ai/langflow/blob/main/docs/docs/Deployment/deployment-kubernetes.md)</sup><sup>[[3]](https://github.com/langflow-ai/langflow/blob/main/docs/docs/deployment/kubernetes.md)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/78ab049b-7fb2-4771-88f5-42287d2c70b9?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/78ab049b-7fb2-4771-88f5-42287d2c70b9?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/78ab049b-7fb2-4771-88f5-42287d2c70b9?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/78ab049b-7fb2-4771-88f5-42287d2c70b9?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/78ab049b-7fb2-4771-88f5-42287d2c70b9?feedback_type=hallucination) | [Other](https://app.dosu.dev/response-feedback/78ab049b-7fb2-4771-88f5-42287d2c70b9?feedback_type=other)</sup>
