### DISCUSSION TITLE
Accessing files/artifacts via path

### DISCUSSION THREAD

**Discussion by tushar-kloud** [langflow-ai/langflow#6264] [Q&A]
I am searching for the location where the flow artifacts and database files are created and stored in memory, specifically through the path (directory location). My goal is to make a copy of the necessary artifacts so that I can reuse them when creating a duplicate of the service. I will be using Docker to set up the LangFlow service.

**Comment by dosubot** [comment]
Hey @tushar-kloud! 👋 I'm here to help you with any bugs, questions, or contributions you have. Let's tackle this together!


Langflow stores flow artifacts and database files in the following default locations:

- **Linux/WSL2**: `home/<username>/.cache/langflow/`
- **MacOS**: `/Users/<username>/Library/Caches/langflow/`

You can access these directories to copy the files for duplicating the LangFlow service using Docker. Additionally, you can customize the storage location by setting the `LANGFLOW_CONFIG_DIR` environment variable. In a Docker setup, you can specify this environment variable in your `docker-compose.yml` file, as shown below:

```yaml
version: "3.8"

services:
  langflow:
    image: langflowai/langflow:latest
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      - LANGFLOW_CONFIG_DIR=/var/lib/langflow
    volumes:
      - langflow-data:/var/lib/langflow

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data

volumes:
  langflow-postgres:
  langflow-data:
```

This configuration will store the logs, file storage, monitor data, and secret keys in the `/var/lib/langflow` directory within the Docker container, which is mapped to the `langflow-data` volume. You can copy this volume to duplicate the LangFlow service <sup>[[1]](https://github.com/langflow-ai/langflow/issues/5552)</sup><sup>[[2]](https://github.com/langflow-ai/langflow/blob/main/docker_example/docker-compose.yml)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/ccf1cadb-f73a-4184-bd8a-186a3a8bf48a?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/ccf1cadb-f73a-4184-bd8a-186a3a8bf48a?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/ccf1cadb-f73a-4184-bd8a-186a3a8bf48a?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/ccf1cadb-f73a-4184-bd8a-186a3a8bf48a?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/ccf1cadb-f73a-4184-bd8a-186a3a8bf48a?feedback_type=hallucination) | [Other](https://app.dosu.dev/response-feedback/ccf1cadb-f73a-4184-bd8a-186a3a8bf48a?feedback_type=other)</sup>
