### ISSUE TITLE
Request for ARM64 Support in LangFlow Docker Images

### ISSUE THREAD

**Issue by tohboeh5** [langflow-ai/langflow#1976]
Thanks for creating such a nice project!

I want to host langflow using docker image on ARM64 device (raspberry pi) but it seems that support only and64.
Is there any plans to add support for ARM64 architecture in Docker images?

**Comment by devinbost** [comment]
Any updates on this? 
It would really help with testing & development.

**Comment by tohboeh5** [comment]
> Hi, @tohboeh5. I'm [Dosu](https://dosu.dev), and I'm helping the langflow team manage their backlog. I'm marking this issue as stale.
> 
> **Issue Summary:**
> 
> * Request for ARM64 architecture support for LangFlow Docker images.
> * Current support is limited to amd64, affecting devices like Raspberry Pi.
> * Suggestion to modify GitHub Actions workflow to include ARM64 builds.
> * Positive community interest and inquiry from @devinbost about updates.
> 
> **Next Steps:**
> 
> * Please confirm if this issue is still relevant with the latest version of the langflow repository by commenting here.
> * If there is no further activity, this issue will be automatically closed in 7 days.
> 
> Thank you for your understanding and contribution!

This issue is not solved, and it seemed to be required for some developers.
Please consider to unmark stale.

**Comment by n0one42** [comment]
+1 for ARM64 support, especially for macOS

I also need the ARM64 version for macOS, as I believe many developers do. macOS is widely used for development, and with the increasing adoption of Apple Silicon (M-series chips) in MacBooks and other Mac devices, ARM64 support becomes crucial.

Specifically, I need this for my M-chip MacBook. The current x86_64 images are not natively compatible, leading to performance issues when running through emulation.

Adding ARM64 support would greatly improve the development experience for those of us using Apple Silicon Macs, allowing us to run LangFlow Docker images natively and efficiently.

This enhancement would make LangFlow more accessible and performant for a growing segment of developers and users. It would also align with the trend of major software projects providing ARM64 support for broader compatibility.

**Comment by robwilkes** [comment]
+1 for arm64 support

**Comment by robwilkes** [comment]
I've submitted a PR for this.
https://github.com/langflow-ai/langflow/pull/5474

The docker hub images built fine.

In the meantime can use:
```
version: "3.8"

services:
  langflow:
    image: robwilkes/langflow:latest # <--- this
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
    volumes:
      - langflow-data:/app/langflow

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data

volumes:
  langflow-postgres:
  langflow-data:
```

I won't be rebuilding/updating/supporting the images I built.
