### ISSUE TITLE
Docker Compose: PermissionError: [Errno 13] Permission denied: '/var/lib/langflow/secret_key'

### ISSUE THREAD

**Issue by brylie** [langflow-ai/langflow#2440]
On a fresh Ubuntu server, I follow the instructions on the [Langflow Docker deployment documentation](https://docs.langflow.org/deployment/docker). When running `docker compose up`, I get the following error in the `langflow` service:

> PermissionError: [Errno 13] Permission denied: '/var/lib/langflow/secret_key'

**To Reproduce**
1. Create an Ubuntu VPS instance
2. Git clone the repository
3. cd to the `docker_example` directory
4. run `docker compose up`
5. See error

**Comment by blazux** [comment]
Got the same error here, I've with few older version of the docker image, same result each time.

**Comment by BrandonBordeaux** [comment]
I've worked around the permissions issue by using a Dockerfile to create and change the ownership of `/var/lib/langflow`, but that only lead to another startup issue (see Langflow discord https://discord.com/channels/1116803230643527710/1256237409692029013/1256237409692029013).

I see the [docker-compose.yml](https://github.com/langflow-ai/langflow/blob/main/docker_example/docker-compose.yml) has an updated config path `/app/langflow` now, but that leads to the same permissions issue.

**Comment by brylie** [comment]
I've opened a pull request as a proof-of-concept. I'm on my mobile and coding with GitHub Copilot so can't currently test the PR. Also, I'm not sure whether the PR is the ideal solution, so opened it mainly to continue the discussion 🙂

**Comment by carlosrcoelho** [comment]
Hi @brylie  ,

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by mexicanhatman** [comment]
> ADD in your compose:
> 
> services: langflow: image: langflowai/langflow user: root

This worked for me. Thanks!

**Comment by Kickbut101** [comment]
I have mine working by adjusting the volume for the langflow service from /app/langflow to /app

```
services:
  langflow:
    image: langflowai/langflow:latest # or another version tag on https://hub.docker.com/r/langflowai/langflow
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - langflow-data:/app
```

**Comment by cande1gut** [comment]
Got into the same problem. Here is a modified docker-compose file that fixes the folder permissions:

```yaml
services:
  fix-langflow-perms:
    image: busybox:latest
    user: "0:0"
    command: >
      sh -c "
        chown -R 1000:0 /app/langflow &&
        chmod -R 755 /app/langflow
      "
    volumes:
      - langflow-data:/app/langflow

  langflow:
    image: langflowai/langflow:latest
    pull_policy: always
    ports:
      - "7860:7860"
    depends_on:
      - postgres
      - fix-langflow-perms
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      - LANGFLOW_CONFIG_DIR=/app/langflow
    volumes:
      - langflow-data:/app/langflow

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data

volumes:
  langflow-postgres:
  langflow-data:
```
