### ISSUE TITLE
LANGFLOW_VARIABLES_TO_GET_FROM_ENVIRONMENT not loading any environment variables

### ISSUE THREAD

**Issue by wi21b030** [langflow-ai/langflow#3021]
### Bug Description

I have a similar issue as #2520, I am using docker compose to run langflow on my machine (docker running on Macbook using Rancher Desktop). For me regardless of which env variables I list in the LANGFLOW_VARIABLES_TO_GET_FROM_ENVIRONMENT variable none of them get loaded into langflow.

When I use my setup none of the variables are visible in the UI:

<img width="1254" alt="Pasted Graphic" src="https://github.com/user-attachments/assets/65a7d94d-c9a6-4e4f-beac-eb371ae93412">

### Reproduction

I am using this setup and I just run `docker compose up -d`:

`docker-compose.yml`:
```yml
services:
  langflow:
    container_name: langflow
    image: langflowai/langflow:1.0.13
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - langflow-data:/app/langflow

  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data

volumes:
  langflow-postgres:
  langflow-data:
```

and my `.env` file (same path as docker compose file) looks like this:

```txt
LANGFLOW_DATABASE_URL=postgresql+psycopg://langflow:langflow@postgres:5432/langflow
LANGFLOW_STORE_ENVIRONMENT_VARIABLES=true
LANGFLOW_VARIABLES_TO_GET_FROM_ENVIRONMENT=‘[“AZURE_OPENAI_API_KEY” , ”AZURE_OPENAI_API_ENDPOINT",  "PGVECTOR_CONNECTION_STRING"]' # variables that I want to be added
AZURE_OPENAI_API_KEY=key # recognized global variable
AZURE_OPENAI_API_ENDPOINT=endpoint # custom environment variable
PGVECTOR_CONNECTION_STRING=postgresql+psycopg://langflow:langflow@postgres:5432/langflow # custom environment variable
```

### Expected behavior

I expect the variables I listed in the LANGFLOW_VARIABLES_TO_GET_FROM_ENVIRONMENT variable to be loaded correctly into langflow (regardless of wether or not they are recognized global variables or custom variables)

### Operating System

Using Docker

### Langflow Version

1.0.13

### Python Version

None
