### ISSUE TITLE
OpenAi Embedding Component: Error Building Component RedisCache only accepts values that can be pickled.

### ISSUE THREAD

**Issue by HanumanTFM** [langflow-ai/langflow#3561]
### Bug Description

I must say langflow is giving me hard time with various errors, crashes and install that was very challenging. 
running 1.0.16 on docker.

here is my docker-compose.yml

```
version: "3.8"

services:
  langflow:
    build: .
    ports:
      - "7860:7860"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      - LANGFLOW_REDIS_HOST=redis
      - LANGFLOW_REDIS_PORT=6379
      - LANGFLOW_CACHE_TYPE=redis
      - LANGFLOW_AUTO_LOGIN=false
      - LANGFLOW_SUPERUSER=admin
      - LANGFLOW_SUPERUSER_PASSWORD=123456
      - LANGFLOW_WORKERS=1
      - LANGFLOW_AUTO_MIGRATE=true
    volumes:
      - langflow-data:/app/backend/langflow
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  langflow-data:
  postgres-data:
  redis-data:
```

Dockerfile:

```
FROM langflowai/langflow:latest

USER root

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    python3-dev \
    postgresql-client

# Install psycopg2 and redis
RUN pip install psycopg2-binary redis

USER 1000

CMD ["langflow", "run", "--port", "7860"]
```

Error running openAI embedding component: 

```
2024-08-27 06:21:53 langflow-1  |                              TypeError: RedisCache only accepts                 
2024-08-27 06:21:53 langflow-1  |                              values that can be pickled.
```

### Reproduction

Install langflow,
Open any flow that uses openai embedding

### Expected behavior

to work....

### Operating System

docker

### Langflow Version

1.0.16

### Python Version

None

### Screenshot

<img width="988" alt="image" src="https://github.com/user-attachments/assets/f1280232-a646-495a-825d-1b4829d8ef0c">
