### ISSUE TITLE
psycopg2 is missing in image langflowai/langflow-backend 1.0.16 & latest

### ISSUE THREAD

**Issue by Vihos** [langflow-ai/langflow#3568]
### Bug Description

Unable to use langflowai/langflow-backend:1.0.16 and latest with PostgreSQL database, missing library `psycopg2-binary` (or any replacement)
![photo_2024-08-27_13-45-41](https://github.com/user-attachments/assets/c37906f0-1e8e-4512-a9e5-65fe4dd59e28)

My values file:
```yaml
postgresql:
  enabled: true
  fullnameOverride: "langflow-ide-postgresql-service"
  global:
    storageClass: "local-path"
  auth:
    username: "USERNAME"
    password: "PASSWORD_HERE"
    database: "DATABASE_NAME"

langflow:
  frontend:
    service:
      type: NodePort
      port: 8080
  backend:
    env:
      - name: LANGFLOW_AUTO_LOGIN
        value: "False"
    externalDatabase:
      enabled: true
      driver:
        value: "postgresql"
      host:
        value: "langflow-ide-postgresql-service"
      port:
        value: "5432"
      database:
        value: "DATABASE_NAME"
      user:
        value: "USERNAME"
      password:
        valueFrom:
          secretKeyRef:
            key: "password"
            name: "langflow-ide-postgresql-service"
    resources:
      limits:
        nvidia.com/gpu: "1"
    sqlite:
      enabled: false
```

I made a quick fix by adding following line at the end of Dockerfile extending original image but better to update requirements.txt
```
RUN pip install psycopg2-binary
``` 

### Reproduction

1. Deploy Helm chart on Kubernetes of version 1.0.0 with latest langflow release
2. Configure it to use Postgres
3. Backend won't start because of missing library

### Expected behavior

Backend service starts.

### Who can help?

@italojohnny

### Operating System

Debian Linux 12

### Langflow Version

1.0.16

### Python Version

None
