### ISSUE TITLE
Impossible to use behind a proxy with a custom certificate (Cloudflare Zero Trust)

### ISSUE THREAD

**Issue by tristanbes** [langflow-ai/langflow#3821]
### Bug Description

Hello,

I'm using my Mac with a corporate Zero Trust solution (Cloudflare Zero Trust) that requires to add a custom certificate in the keychain and some specific programms (https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/user-side-certificates/install-cloudflare-cert/). 

The console is spammed with messages like 
```
service - Unexpected error occurred: [SSL: service.py:76 CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)
```

It's not possible to run anything that requires http calls

### Reproduction

I tried running the image with: 
```
docker run -it --rm -v ~/workspace/Cloudflare_CA.pem:/tmp/cf.pem -e REQUESTS_CA_BUNDLE=/tmp/cf.pem -p 7860:7860 langflowai/langflow:latest
```

But the project doesn't seem to use the certificate when doing external calls.

### Expected behavior

-

### Operating System

MacOS 14.6.1

### Langflow Version

v1.0.18

### Python Version

None

### Screenshot

![CleanShot 2024-09-16 at 16 16 28@2x](https://github.com/user-attachments/assets/47a7730b-9753-403a-ab7b-aa14c839c213)

**Comment by tristanbes** [comment]
My bad, I ignored the solution from the bot because to me it was like the one I used (my mistake).
Right now I asked our devops to host it on the cloud because I could not afford to loose time working around it

**Comment by carlosrcoelho** [comment]
Hey @tristanbes 
Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to help you.

**Comment by zizzfizzix** [comment]
For those finding this issue via search, I needed to get langflow to accept self-signed certificates that I signed with my own root CA cert, so I wanted to add the root certificate to the docker image, and this is how I solved it:
```yaml
# ./docker-compose.yaml
services:
  langflow:
    build: . # Use the Dockerfile in the current directory
    pull_policy: always               # set to 'always' when using 'latest'
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      # accept self-signed certificates https://github.com/langflow-ai/langflow/issues/3821#issuecomment-2353068593
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    volumes:
      - langflow-data:/app/langflow

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    expose:
      - 5432
    volumes:
      - langflow-postgres:/var/lib/postgresql/data

volumes:
  langflow-postgres:
  langflow-data:
```

```yaml
# ./Dockerfile
# Use the langflowai/langflow:latest image as the base
FROM langflowai/langflow:latest

# Copy your root CA certificate to the container
COPY ./certs/your-rootCA.pem /usr/local/share/ca-certificates/your-rootCA.crt

# Switch to root to update the CA store
USER root
RUN update-ca-certificates

# Switch back to the original user
USER user
```
