### ISSUE TITLE
Error 400 API mistralAI

### ISSUE THREAD

**Issue by abelBEDOYA** [langflow-ai/langflow#5335]
### Bug Description

Hello, 

I've been using langlfow to build a chatbot, a RAG and now an agent which can access a calculator tool. 
Using OpenAI model with its key works fine. However when I try so with MistralAI it runs into this error:

```
An error occured in the Agent Component, stopping your flow. See below for more details.
Error details:
HTTPStatusError

    Details: Error response 400 while fetching https://api.mistral.ai/v1/chat/completions: {"object":"error","message":"Tool call id has to be defined.","type":"invalid_request_error","param":null,"code":null}
```

The mistral model that is been used is misrtal-large-latest. If the model doesn't conclude that the tool has to be used, the chat doesn't run into this error. This happens with every model.

![Screenshot from 2024-12-18 14-28-38](https://github.com/user-attachments/assets/928a721f-15c8-4efa-929d-d17167a676a1)

![Screenshot from 2024-12-18 14-30-26](https://github.com/user-attachments/assets/92f6015f-c0cd-4881-b19d-bbfab8bdeae5)

![Screenshot from 2024-12-18 14-30-36](https://github.com/user-attachments/assets/509fdbc2-f435-4965-ab4e-caefc5f8a3d6)

### Reproduction

1. Run langflow with docker:
`docker compose up`

with this docker

```
version: "3.8"

services:
  langflow:
    image: langflowai/langflow:latest # or another version tag on https://hub.docker.com/r/langflowai/langflow 
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
    volumes:
      - langflow-data:/app/langflow
```

2. Set the calculator agent flow
3. Ask for a calculation result

### Expected behavior

A new message which depends on the outcome of the calculator (calculator tool should have been used) with the correct result.

### Operating System

Ubuntu 22.04 (docker)

### Langflow Version

1.1.1

### Python Version

3.11

### Flow File

[Simple Agent.json](https://github.com/user-attachments/files/18184882/Simple.Agent.json)
