### ISSUE TITLE
Crash on startup with Postgres - constraint "fk_flow_user_id_user" for relation "flow" already exists 

### ISSUE THREAD

**Issue by devinbost** [langflow-ai/langflow#5371]
### Bug Description

LangFlow is crashing on startup when postgres is enabled. It's giving this exception:

```
[12/19/24 18:47:43] ERROR    2024-12-19 18:47:43 - ERROR    - b2fa308044b5_add_unique_constraints - Error during upgrade: (psycopg2.errors.DuplicateObject)    b2fa308044b5_add_unique_constraints.py:51
                             constraint "fk_flow_user_id_user" for relation "flow" already exists                                                                                                       
                                                                                                                                                                                                        
                             [SQL: ALTER TABLE flow ADD CONSTRAINT fk_flow_user_id_user FOREIGN KEY(user_id) REFERENCES "user" (id)]                                                                    
                             (Background on this error at: https://sqlalche.me/e/20/f405)Traceback (most recent call last):  
```

I've experienced this on several of the recent LangFlow versions (starting I think around 1.0.19).

Interestingly, it's saying it's trying to upgrade, but the data directories are totally clear.

Detailed log is here: 
[docker-compose-postgres-alembic2.log](https://github.com/user-attachments/files/18202040/docker-compose-postgres-alembic2.log)


### Reproduction

1. Start LangFlow with this docker-compose.yaml file:

```
version: "0.4.12"

networks:
  langflow-network:
    driver: bridge

services:
  langflow3:
    image: langflowai/langflow-ep:v1.1.1.dev11 
    ports:
      - "7860:7860"
    command: ["langflow", "run", "--env-file", "/app/.env", "--host", "0.0.0.0", "--port", "7860"]
    working_dir: /app
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      - COLUMNS=200
    volumes:
      - ./langflow-tmp/langflow-data:/app/langflow
      - ./langflow-tmp/langflow-app-data:/app/data
      - ./langflow-tmp/cache:/app/data/.cache
    networks:
      - langflow-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - ./langflow-tmp/langflow-postgres:/var/lib/postgresql/data
    networks:
      - langflow-network
```

### Expected behavior

LangFlow should start as expected

### Who can help?

@jord

### Operating System

Mac M1

### Langflow Version

langflowai/langflow-ep:v1.1.1.dev11

### Python Version

3.10

### Screenshot

_No response_

### Flow File

_No response_
