### ISSUE TITLE
Unable to specify Redis password

### ISSUE THREAD

**Issue by Martin-WMM** [langflow-ai/langflow#5546]
### Bug Description

I am trying to deploy the Langflow project using Docker Compose. When I attempt to set `LANGFLOW_CACHE_TYPE=memory`, I found that I am unable to set the Redis password. In the `__init__` method of the `RedisCache` class, there is a `url` parameter, but the environment variable cannot be passed, or I am unsure how to pass it.

The `RedisCache` class is
```python
class RedisCache(AsyncBaseCacheService, Generic[LockType]):
    """A Redis-based cache implementation.

    This cache supports setting an expiration time for cached items.

    Attributes:
        expiration_time (int, optional): Time in seconds after which a cached item expires. Default is 1 hour.

    Example:
        cache = RedisCache(expiration_time=5)

        # setting cache values
        cache.set("a", 1)
        cache.set("b", 2)
        cache["c"] = 3

        # getting cache values
        a = cache.get("a")
        b = cache["b"]
    """

    def __init__(self, host="localhost", port=6379, db=0, url=None, expiration_time=60 * 60) -> None:
        """Initialize a new RedisCache instance.

        Args:
            host (str, optional): Redis host.
            port (int, optional): Redis port.
            db (int, optional): Redis DB.
            url (str, optional): Redis URL.
            expiration_time (int, optional): Time in seconds after which a
                cached item expires. Default is 1 hour.
        """
        try:
            from redis.asyncio import StrictRedis
        except ImportError as exc:
            msg = (
                "RedisCache requires the redis-py package."
                " Please install Langflow with the deploy extra: pip install langflow[deploy]"
            )
            raise ImportError(msg) from exc
        logger.warning(
            "RedisCache is an experimental feature and may not work as expected."
            " Please report any issues to our GitHub repository."
        )
        if url:
            self._client = StrictRedis.from_url(url)
        else:
            self._client = StrictRedis(host=host, port=port, db=db)
        self.expiration_time = expiration_time
# ...
```

I'm not exactly sure how to configure it, but I really appreciate your response!

### Reproduction

1. Docker Compose deploy
```yml
  langflow:
    image: langflowai/langflow:latest
    ports:
      - "32604:7860"
    depends_on:
      - postgresql
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://root:zjb_pgsql_123@postgresql:5432/lang-workflow
      - LANGFLOW_CACHE_TYPE=redis
      - LANGFLOW_REDIS_HOST=redis
      - LANGFLOW_REDIS_PORT=6379
      - LANGFLOW_REDIS_PASSWORD=${REDIS_PASSWORD} # redis password not work
      - LANGFLOW_AUTO_LOGIN=false
      - LANGFLOW_SUPERUSER=admin
      - LANGFLOW_SUPERUSER_PASSWORD=admin_123
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
    volumes:
      - ./data/langflow-data:/app/langflow
```
2. Start the service by docker compose: `docker compose up -d`

### Expected behavior

Start the Langflow project normally

### Who can help?

@italojohnny

### Operating System

Linux

### Langflow Version

1.1.1

### Python Version

3.12
