### ISSUE TITLE
Support for system TLS certificate trust store and custom certificates

### ISSUE THREAD

**Issue by zizzfizzix** [langflow-ai/langflow#5717]
### Feature Request

Langflow should trust and respect certificates in the system trust store, or provided to Langflow directly so it can communicate with hosts using self-signed certificates.

Since Langflow uses `httpx` the [implementation could be relatively simple](https://www.python-httpx.org/advanced/ssl/#configuring-client-instances), however [looking through the code](https://github.com/search?q=repo%3Alangflow-ai%2Flangflow%20httpx&type=code) there doesn't appear to be a single `httpx` instance which config can be modified, and it might require some refactoring.

Right now, using e.g. the API Request component to connect to a host using a self-signed certificate will result in `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)`. Providing a `curl --insecure https://hostname` command seems to end in another error, so is unfeasible as a workaround.

### Motivation

I have other services I want Langflow to interface with that are using HTTPS with self-signed certificates in an internal `.test` DNS zone, it's infeasible to use HTTP and impossible to get a trusted certificate for a reserved TLD.

There's also another issue/use case mentioning [Langflow behind a Cloudflare Zero Trust proxy](https://github.com/langflow-ai/langflow/issues/3821).
None of the potential solutions there are working to solve this.

### Your Contribution

Unfortunately I'm not a python dev so feel a bit out of depth to create a PR.

**Comment by evolu8** [comment]
Any movement on this? It's really quite critical.

**Comment by Alex-FIR-IT** [comment]
You can add your self-signed cerfificate(s) by extending requests' and httpx's default bundle. 

1) The first step is to inject your certificate into your container/pod. 

For docker it would be someething like:

```docker-compose
services:
  langflow:
    image: langflowai/langflow:1.12.1
    ports:
      - "7860:7860"
    environment:
      - CUSTOM_CA_CERT_PATH=/etc/ssl/custom/ca.crt
    volumes:
      - type: bind
        source: ./cert # it's just a local directory with your ca.crt file
        target: /etc/ssl/custom/
        read_only: true
```
In k8s:

```yaml
deploy:
...
  script:
    - helm upgrade -i --namespace ${NAMESPACE} ${APP}
      --set env.CUSTOM_CA_CERT_PATH="$CUSTOM_CA_CERT_PATH" # a var in gitlab
      --set-file customCaCert=$CUSTOM_CA_CERT # a file var in gitlab
```

values.yaml:
```yaml
env: {}
```

helm templates:

```
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "AppSettings.fullname" . }}-custom-ca
type: Opaque
stringData:
  ca.crt: {{ .Values.customCaCert | quote }}
---
apiVersion: apps/v1
kind: Deployment
...
spec:
  ...
  template:
    ...
    spec:
      ...
      containers:
           ...
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: custom-ca
              mountPath: /etc/ssl/custom
              readOnly: true
      volumes:
        - name: custom-ca
          secret:
            secretName: {{ include "AppSettings.fullname" . }}-custom-ca

```


2) The second step is to create docker-entrypoint.sh located near to the Dockerfile:

```sh
#!/bin/sh
set -e

CUSTOM_CA_SRC="${CUSTOM_CA_CERT_PATH:-/etc/ssl/custom/ca.crt}"
COMBINED_BUNDLE="/tmp/combined-ca-bundle.pem"

if [ -f "$CUSTOM_CA_SRC" ]; then
  # certifi's bundle is what requests/httpx use by default anyway
  CERTIFI_BUNDLE=$(python -c "import certifi; print(certifi.where())")
  cat "$CERTIFI_BUNDLE" "$CUSTOM_CA_SRC" > "$COMBINED_BUNDLE"

  export REQUESTS_CA_BUNDLE="$COMBINED_BUNDLE"
  export SSL_CERT_FILE="$COMBINED_BUNDLE"
  echo "Combined CA bundle written to $COMBINED_BUNDLE"
else
  echo "No custom CA cert found at $CUSTOM_CA_SRC, skipping"
fi

exec "$@"

``` 

3) The third step is to add this entrypoint into your Dockerfile:

```Dockerfile
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["uv", "run", "langflow", "run", "--host", "0.0.0.0", "--port", "7860"]
```
