### ISSUE TITLE
Unable to connect to clickhouse as vector storage

### ISSUE THREAD

**Issue by ashkart** [langflow-ai/langflow#5954]
### Bug Description

It seems app always looking for clickhouse on default port 8123.

On screenshot in component's settings there is 8124 port, but Exception shows 8123. There is another instanse on 8123 indeed, that because exception says status code is 403, nor 404 or 50*.

### Reproduction

1) lanflow:latest docker image is deployed
2) clickhouse docker is deployed (v23) with forwarding to custom port
```yml
clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8124:8123"
    environment:
      - CLICKHOUSE_USER=max
      - CLICKHOUSE_PASSWORD=123
      - CLICKHOUSE_DB=max
```

3) create new Basic Prompting project in LF.
4) add clickhouse vector storage.
5) Fill clickhouse components required fields
6) Try run clickhouse component

### Expected behavior

"Clickhouse build successfully" status statement alert, and working connected embedding workflow also.

### Operating System

Linux mint 22

### Langflow Version

langflowai/langflow:latest

### Python Version

None

### Screenshot

![Image](https://github.com/user-attachments/assets/03e78ae6-efde-42bc-a756-e59f7eb7d3b4)
