### ISSUE TITLE
When LANGFLOW_LOAD_FLOWS_PATH is set and when docker_example is being used, when bringing up the service 2nd time, langflow crashes

### ISSUE THREAD

**Issue by shrikrishnaholla** [langflow-ai/langflow#6054]
### Bug Description

I wanted to import the flow I had built in my dev environment and run it headlessly in a staging environment. `LANGFLOW_LOAD_FLOWS_PATH` seemed like the right fit. It did work as intended when I brought up the service the first time. However, in subsequent starts, langflow crashes.

The specific error message when the crash happens is

```
langflow-1  | sqlalchemy.exc.IntegrityError: (psycopg.errors.ForeignKeyViolation) insert or update on table "flow" violates foreign key constraint "flow_folder_id_fkey"
langflow-1  | DETAIL:  Key (folder_id)=(c9acccee-a2cc-479d-8731-e3671092b63f) is not present in table "folder".
langflow-1  | [SQL: UPDATE flow SET updated_at=%(updated_at)s::TIMESTAMP WITHOUT TIME ZONE, folder_id=%(folder_id)s::UUID WHERE flow.id = %(flow_id)s::UUID]
langflow-1  | [parameters: {'updated_at': datetime.datetime(2025, 2, 1, 5, 47, 6, 304320, tzinfo=datetime.timezone(datetime.timedelta(0), 'UTC')), 'folder_id': 'c9acccee-a2cc-479d-8731-e3671092b63f', 'flow_id': UUID('21b6f740-e1f2-4a24-a650-4379c7b52a66')}]
langflow-1  | (Background on this error at: https://sqlalche.me/e/20/gkpj)
```
I think either:
1. Langflow has stored the name of the folder in my previous environment (which is its default folder only, I hadn't created any folder manually) and it's panicking because it's not finding the default folder in the newer environment. But this doesn't explain why it worked the first time I brought up the service.
2. It's trying to create a new folder on each startup and the id of folder is not matching between startups. Also seems unlikely to be the case, but it's possible.

### Reproduction

1. In one environment, create a flow. Take an export as JSON
2. In another environment, create a folder called "flows". Move the JSON there
3. In the 2nd environment, create this `docker-compose.yml` file:
```yml
version: "3.8"

services:
  langflow:
    image: langflowai/langflow:latest # or another version tag on https://hub.docker.com/r/langflowai/langflow
    pull_policy: always               # set to 'always' when using 'latest' image
    command: python -m langflow run --backend-only --host 0.0.0.0 --port 7860
    # user: root                           # uncomment this if you get permissions issues
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - LANGFLOW_CONFIG_DIR=/app/langflow
      - LANGFLOW_AUTO_SAVING=false
      - LANGFLOW_AUTO_LOGIN=true
      - LANGFLOW_LOAD_FLOWS_PATH=/app/langflow-flows
    volumes:
      - langflow-data:/app/langflow
      - ./flows:/app/langflow-flows

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    expose:
      - 5432
    volumes:
      - langflow-postgres:/var/lib/postgresql/data

volumes:
  langflow-postgres:
  langflow-data:

```
4. Bring up the service. It will start up normally
5. Tweak any parameter in the docker-compose.yml, which causes docker to re-create the container (In my case, I had added the `--backend-only` flag to the `command` which triggered the errors). It will start throwing the error above

### Expected behavior

Langflow should start normally even on repeated restarts when flows are mounted through `LANGFLOW_LOAD_FLOWS_PATH`

### Who can help?

@italojohnny @ogabrielluiz 

### Operating System

KDE Neon 5.65 (Linux, based on Debian). Docker version 27.4.1, build b9d17ea

### Langflow Version

v1.1.3

### Python Version

None

### Screenshot

![Image](https://github.com/user-attachments/assets/0d94fc09-655f-47cb-ba44-2d9ca64de03b)

### Flow File

The flow has credentials so can't really share it, but it must be possible to replicate this with any basic flow as well
