### ISSUE TITLE
Issue: Celery Module Not Found in Docker Container

### ISSUE THREAD

**Issue by sungreong** [langflow-ai/langflow#6501]
#### Description
When running the Langflow with Docker Compose, the flower service fails with "No module named celery" error. This started happening suddenly with the image `langflowai/langflow-backend:1.1.4`.

#### Environment
- Langflow Backend Version: 1.1.4
- Docker Compose Version: 3.3
- OS: Linux

#### Configuration
docker-compose.yml configuration for the flower service:

```

  backend: &backend
    image: "langflowai/langflow-backend:1.1.4"
    depends_on:
      - db
      - broker
      - result_backend
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=langflow-traefik
      - traefik.http.routers.langflow-stack-backend-http.rule=PathPrefix(`/api/v1`) || PathPrefix(`/docs`) || PathPrefix(`/health`)
      - traefik.http.services.langflow-stack-backend.loadbalancer.server.port=7860

  db:
    image: postgres:15.4
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - traefik-public
      - default
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - "traefik.http.routers.langflow-stack-pgadmin-http.rule=Host(`pgadmin.${DOMAIN:-localhost}`)"
      - traefik.http.services.langflow-stack-pgadmin.loadbalancer.server.port=5050

  result_backend:
    image: redis:6.2.5
    env_file:
      - .env
    ports:
      - 6379:6379

  celeryworker:
    <<: *backend
    env_file:
      - .env
    command: /bin/sh -c "python -m celery -A langflow.worker.celery_app worker --loglevel=INFO --concurrency=6 -n lf-worker@%h -P eventlet"
    healthcheck:
      test: "exit 0"
    restart: unless-stopped

  flower:
    <<: *backend
    env_file:
      - .env
    networks:
      - default
    environment:
      - FLOWER_PORT=5555
    command: >
      /bin/sh -c "
      python -m celery -A langflow.worker.celery_app --broker=${BROKER_URL?Variable not set} flower --port=5555
      "
```

#### Error Log

Attaching to deploy_flower_1
flower_1 | /app/.venv/bin/python: No module named celery
flower_1 | /app/.venv/bin/python: No module named celery
flower_1 | /app/.venv/bin/python: No module named celery

#### Steps to Reproduce
1. Run `docker-compose up -d`
2. Check logs with `docker-compose logs flower`
3. See the "No module named celery" error

#### Expected Behavior
The flower service should start successfully and monitor the Celery workers.

#### Attempted Solutions
1. Tried installing celery directly in the container:
2. Tried using python3 instead of python
3. Tried using --user flag with pip install

#### Question
Is there a problem with the virtual environment setup in the 1.1.4 image?

![Image](https://github.com/user-attachments/assets/e2eb331b-3a60-40c5-9471-00d2d3d530f4)

### Reproduction

1. Run `docker-compose up -d`
2. Check logs with `docker-compose logs flower`
3. See the "No module named celery" error

### Expected behavior

Is there a problem with the virtual environment setup in the 1.1.4 image?

### Operating System

Ubuntu22.04

### Langflow Version

1.1.4

### Python Version

None
