### ISSUE TITLE
Flows not stored when using multiple users

### ISSUE THREAD

**Issue by savvaki** [langflow-ai/langflow#6695]
### Bug Description

Flows are not saved on self-hosted langflow when multiple users are enabled. When I log out and log back in my flows don't load, When I used a single user the system worked. Note that an external postgres database is used specified in `LANGFLOW_DATABASE_URL`:

```
 langflow:
    image: langflowai/langflow:latest
    container_name: langflow
    restart: unless-stopped
    environment:
      - LANGFLOW_AUTO_LOGIN=false
      - LANGFLOW_SUPERUSER=admin
      - LANGFLOW_SUPERUSER_PASSWORD=jkhaskjdhASDkjlashdkjahsc
      - DO_NOT_TRACK=true
      - LANGFLOW_WORKERS=1
      - LANGFLOW_CONFIG_DIR=/app/langflow
      - LANGFLOW_DATABASE_URL=postgresql://username:password@postgres-db:5432/langflow-db 
    user: root
    depends_on:
      - postgres-db
    volumes:
      - /mnt/langflow-data:/app/langflow
    ports:
      - "7860:7860"
  ```

### Reproduction

1. Use this docker compose:
```
 langflow:
    image: langflowai/langflow:latest
    container_name: langflow
    restart: unless-stopped
    environment:
      - LANGFLOW_AUTO_LOGIN=false
      - LANGFLOW_SUPERUSER=admin
      - LANGFLOW_SUPERUSER_PASSWORD=jkhaskjdhASDkjlashdkjahsc
      - DO_NOT_TRACK=true
      - LANGFLOW_WORKERS=1
      - LANGFLOW_CONFIG_DIR=/app/langflow
      - LANGFLOW_DATABASE_URL=postgresql://username:password@postgres-db:5432/langflow-db 
    user: root
    depends_on:
      - postgres-db
    volumes:
      - /mnt/langflow-data:/app/langflow
    ports:
      - "7860:7860"
  ```
2. Login to the admin account using `admin` as username and `jkhaskjdhASDkjlashdkjahsc` as password
3. Create some flows
4. Logout
5. Log back in. 
6. The flows are empty, it does not show any flows.

### Expected behavior

Flows should save correctly for each user. Currently flows disappear after I log out.

### Who can help?

@italojohnny @ogabrielluiz 

### Operating System

Amazon Linux 2023

### Langflow Version

1.1.4

### Python Version

3.12

### Screenshot

![Image](https://github.com/user-attachments/assets/59e68cd4-0c28-4b2c-99c1-4c6bdc1f76f1)
