### ISSUE TITLE
Could not open a template: Cannot read properties of undefined (reading data)

### ISSUE THREAD

**Issue by qdrddr** [langflow-ai/langflow#6910]
### Bug Description

When clicking on any templates, getting an error message:
```
Could not create flow
Cannot read properties of undefined (reading 'data')
```
While I can create an empty flow and add nodes.

![Image](https://github.com/user-attachments/assets/218d1f94-5a77-49a2-9c63-04d298e77d2e)

### Reproduction

deployed on the k8s cluster using the official helm-chart. tested with both externalDB enabled and disables (SQLite).
```yaml
imagePullSecrets: []

nameOverride: "langflow-service"
# Override for the name of the helm deployment
# Note: using `langflow` as service name causes
# env var collision when deploying on openshift
# https://github.com/langflow-ai/langflow/issues/4330#issuecomment-2459097917
fullnameOverride: "langflow-service"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the
  # fullname template
  name: ""

ingress:
  enabled: false

  hosts:
    - host: skynet-langflow.mywebsite.com
      paths: /
  tls:
    - secretName: skynet-langflow.mywebsite.com-tls
      hosts:
        - skynet-langflow.mywebsite.com

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  runAsGroup: 1000

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true
  runAsGroup: 1000


langflow:
  global:
    image:
      #https://hub.docker.com/r/langflowai/langflow/tags?name=1.
      tag: "1.1.4"
  backend:
    replicaCount: 1
    service:
      type: ClusterIP
      port: 7860
    backendOnly: true
    numWorkers: 1
    image:
      repository: langflowai/langflow
      imagePullPolicy: IfNotPresent
      tag: latest
    command:
      - python
      - -m
      - langflow
      - run
      - --host
      - 0.0.0.0
      - --backend-only
    resources:
      requests:
        cpu: 0.5
        memory: 1Gi
      # limits:
      #   cpu: 0.5
      #   memory: 1Gi
    probe:
      failureThreshold: 3
      periodSeconds: 10
      timeoutSeconds: 5
      initialDelaySeconds: 5
    env:
      - name: LANGFLOW_PORT
        value: "7860"
      - name: LANGFLOW_ALEMBIC_LOG_FILE
        value: "/app/db/alembic.log"
      - name: LANGFLOW_UPDATE_STARTER_PROJECTS
        value: "false"
      - name: DO_NOT_TRACK
        value: "true"
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: 9090
      prometheus.io/path: "/metrics"

    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      runAsGroup: 1000

    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
      runAsGroup: 1000

    externalDatabase:
      enabled: true
      driver:
        value: "postgresql"
      host:
        value: "langflow-pg"
      port: 
        value: "5432"
      user:
        value: "user"
      password:
        valueFrom:
          secretKeyRef:
            key: password
            name: langflow-secret
      database:
        value: "langflowDB"

    volumes:
      - name: flows
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: data
        emptyDir: {}
      - name: db
        emptyDir: {}

    volumeMounts:
      - name: flows
        mountPath: /app/flows
        readOnly: false
      - name: tmp
        mountPath: /tmp
        readOnly: false
      - name: data
        mountPath: /app/data
        readOnly: false
      - name: db
        mountPath: /app/db
        readOnly: false

    sqlite:
      enabled: true
      volume:
        size: "5Gi"
        existingStorageClassName: "local-path-retain"
        # If you want the chart to create storage classes, then don't set
        # existingStorageClassName name and provide configuration values
        # for the storage class. The settings vary based on cloud
        # provider. Below are examples for AWS, GCP, and Azure.

        # For AWS
        # storageClass:
        #  provisioner: kubernetes.io/aws-ebs
        #  type: gp2
        #  fsType: ext4
        #  extraParams:
        #     iopsPerGB: "10"

        # For GCP
        # storageClass:
        #   provisioner: kubernetes.io/gce-pd
        #   type: pd-ssd
        #   fsType: ext4
        #   extraParams:
        #      replication-type: none

        # For Azure
        # storageClass:
        #   provisioner: kubernetes.io/azure-disk
        #   fsType: ext4
        #   type: managed-premium
        #   extraParams:
        #     storageaccounttype: Premium_LRS
        #     kind: Managed
        #     cachingmode: ReadOnly
        storageClass: {}

    # autoLogin: true|false
    # superuser: <superuser login>
    # superuserPassword: <superuser password>
    # secretKey: <encryption key, optional>
    # newUserIsActive: true|false

  frontend:
    enabled: true
    replicaCount: 1
    service:
      type: ClusterIP
      port: 8080
    image:
      repository: langflowai/langflow-frontend
      imagePullPolicy: IfNotPresent
      tag: latest
    resources:
      requests:
        cpu: 0.3
        memory: 512Mi
      # limits:
      #   cpu: 0.3
      #   memory: 512Mi
    probe:
      failureThreshold: 3
      periodSeconds: 10
      timeoutSeconds: 5
      initialDelaySeconds: 5
    nodeSelector: {}

    tolerations: []

    affinity: {}
    podAnnotations: {}

    volumes:
      - name: tmp
        emptyDir: {}

    volumeMounts:
      - name: tmp
        mountPath: /tmp
        readOnly: false

secretProvider:
  enabled: false

postgresql:
  enabled: false
```

### Expected behavior

be able to open templates

### Operating System
k8s rancher rke2: v1.27
Ubuntu 22.4

### Langflow Version
tested both versions:
1.2.0 and 1.1.4

frontend & backend were always of the same versions, like ethis:
- langflowai/langflow-frontend:1.2.0
- langflowai/langflow:1.2.0

### Helm-Chart Version
0.1.1

None

### Logs from the backend:

```log
LF_CHART_EXTERNALDB_DRIVER is set, using external database at langflow-cnpg-rw
Starting Langflow v1.2.0...
/app/.venv/lib/python3.12/site-packages/sqlmodel/orm/session.py:66: SAWarning: DELETE statement on table 'flow' expected to delete 26 row(s); 0 were matched.  Please set confirm_deleted_rows=False within the mapper configuration to prevent this warning. (This warning originated from the Session 'autoflush' process, which was invoked automatically in response to a user-initiated operation. Consider using ``no_autoflush`` context manager if this warning happended while initializing objects.)
  results = super().execute(
sys:1: SAWarning: DELETE statement on table 'flow' expected to delete 26 row(s); 0 were matched.  Please set confirm_deleted_rows=False within the mapper configuration to prevent this warning.
╭───────────────────────────────────────────────────────────────────╮
│ Welcome to ⛓ Langflow                                             │
│                                                                   │
│                                                                   │
│ Collaborate, and contribute at our GitHub Repo 🌟                 │
│                                                                   │
│ We collect anonymous usage data to improve Langflow.              │
│ You can opt-out by setting DO_NOT_TRACK=true in your environment. │
│                                                                   │
│ Access http://0.0.0.0:7860                                        │
╰───────────────────────────────────────────────────────────────────╯
```

When I execute from the UI `curl http://langflow-service-backend:7860/all` I do not get a proper response: `{"detail":"Not Found"}`
