### ISSUE TITLE
while using docker example boot up the project, lm studio component not working

### ISSUE THREAD

**Issue by weykon** [langflow-ai/langflow#7262]
### Bug Description

it will export error: Could not retrieve models. Please, make sure the LM Studio server is running.

but while using local dev running, it is ok. 

I'm not sure whether I ignore any necessary settings for docker.

### Reproduction

1. git clone project
2. cd docker_example
3. docker compose up
4. trun on lm studio service
5. add lm studio component in web
6. not working

### Expected behavior

run fine with docker image: langflowai/langflow:latest

### Operating System

macos

### Langflow Version

latest image in docker

### Python Version

None

**Comment by Nakshatra-tec** [comment]
Here's a complete `docker-compose.yml` setup to run Langflow with LM Studio integration, including all necessary configurations:

```yaml
version: '3.8'

services:
  langflow:
    image: langflowai/langflow:latest
    # Use one of these network options:
    network_mode: "host"  # Simplest solution for macOS/Windows
    # OR for custom network:
    # networks:
    #   - langflow-net
    ports:
      - "7860:7860"
    volumes:
      - ./data:/data
    environment:
      - LANGFLOW_HOST=0.0.0.0
      - LANGFLOW_PORT=7860
    restart: unless-stopped

# Uncomment if using custom network:
# networks:
#   langflow-net:
#     driver: bridge
```

### Additional Setup Instructions:

1. **First, ensure LM Studio is properly configured**:
   - Open LM Studio
   - Go to Settings → Server
   - Enable "Allow server connections"
   - Note the port number (default is usually 1234)
   - Make sure it's set to listen on all interfaces (0.0.0.0) not just localhost

2. **Create a directory structure**:
   ```
   docker_example/
   ├── docker-compose.yml
   ├── data/
   │   └── (Langflow will store flows here)
   ```

3. **Start the services**:
   ```bash
   docker compose up -d
   ```

4. **Configure LM Studio in Langflow**:
   - Access Langflow at http://localhost:7860
   - Add an LM Studio component
   - For the endpoint URL use either:
     - `http://localhost:1234` (if using `network_mode: host`)
     - `http://host.docker.internal:1234` (if using bridge network)

### Troubleshooting Tips:

1. If you get connection errors:
   ```bash
   # Test if LM Studio is reachable from host:
   curl http://localhost:1234/v1/models

   # If using bridge network, test from container:
   docker compose exec langflow curl http://host.docker.internal:1234/v1/models
   ```

2. Check LM Studio logs to verify it's receiving requests

3. Verify Docker networking:
   ```bash
   docker network inspect bridge
   ```

This setup should resolve the connection issues between Langflow in Docker and LM Studio running on your host machine. The key is ensuring proper network connectivity between the Docker container and your host services.
