### ISSUE TITLE
Credentials corrupted after container restarts

### ISSUE THREAD

**Issue by qdrddr** [langflow-ai/langflow#7348]
### Bug Description

Saved credentials are not usable after the LangFlow container reboots. The credentials are listed, but not usable. Discussing [here](https://discord.com/channels/1116803230643527710/1117938287601008860/1355336460496277504).

### Reproduction

After I had deployed LangFlow v1.2.0 as a docker container, created a flow added credentials, and restarted the container, my flow no longer can use the saved credentials.

After I manually re-enter the credentials, the flow is functional again until the next container reboots.

### Expected behavior

Preserve the saved credentials after reboots

### Operating System

macOS 15, docker desktop v4.39

### Langflow Version

1.2.0

### Python Version

None

**Comment by qdrddr** [comment]
Here is my docker-compose file:
```yaml
name: langflow
services:
  langflow:
    image: langflowai/langflow:1.2.0 # or another version tag on https://hub.docker.com/r/langflowai/langflow
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    command: python -m langflow run --host 0.0.0.0
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - LANGFLOW_CONFIG_DIR=app/langflow
      - LANGFLOW_MCP_SERVER_ENABLED=true
      - DO_NOT_TRACK=true  # Opt-out of tracking
    volumes:
      - langflow-data:/app/langflow
    # Add extra_hosts to allow container to resolve host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data

volumes:
  langflow-postgres:
  langflow-data:

```

**Comment by hari4742** [comment]
You might need to mention the Dosu bot for it to reply back

> To continue talking to [Dosu](https://dosu.dev/), mention `@dosu`.

**Comment by danielalejandrohc** [comment]
I have the same issue, I have configured Postgres, Global Variables of type Credential is gone, the definition is present, and I see them on the database, but the values looks gets corrupted

**Comment by danielalejandrohc** [comment]
@dosu Check the yaml, this should be storing the values on the database

```
name: langflow
services:
  langflow:
    image: langflowai/langflow:1.2.0 # or another version tag on https://hub.docker.com/r/langflowai/langflow
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    command: python -m langflow run --host 0.0.0.0
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - LANGFLOW_CONFIG_DIR=app/langflow
      - LANGFLOW_MCP_SERVER_ENABLED=true
      - DO_NOT_TRACK=true  # Opt-out of tracking
    volumes:
      - langflow-data:/app/langflow
    # Add extra_hosts to allow container to resolve host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data

volumes:
  langflow-postgres:
  langflow-data:

````
