### ISSUE TITLE
[ MCP Tool ] Why not integrate npx env into Langflow image ?

### ISSUE THREAD

**Issue by helgesander02** [langflow-ai/langflow#7377]
### Feature Request

Currently, Langflow's Docker image supports `uv`, but many MCP server examples rely on the `npx` environment. This creates difficulties when trying to run these examples within Langflow. The documentation mentions that `uvx` is included in the Langflow package, but to use `npx` server commands, an LTS version of Node.js must first be installed. Integrating the `npx` environment into the Langflow image by default would simplify the process and enhance compatibility with MCP server examples.

### Motivation

After setting up Langflow using Docker Compose, I attempted to use Tools (MCP Server Stdio), only to find that it only supports uv. However, many MCP server examples rely on npx, making it challenging to run them within Langflow. I initially experimented with Docker-in-Docker and Docker-outside-of-Docker approaches, but neither provided a satisfactory solution. The documentation clarified that local environments handle this by including Node.js manually. To resolve this, I ended up creating a custom Dockerfile that installs the npx environment and using a build process instead of relying on the default image.

docker_example / Dockfile.npxenv 
```
FROM langflowai/langflow:latest

USER root

RUN apt-get update && apt-get install -y \
    curl \
    && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g npm

RUN node --version && npm --version
```

docker_example / docker-compose.yml
```
services:
  langflow:
    build:
      context: .
      dockerfile: Dockerfile.npxenv
    #image: langflowai/langflow:latest
    pull_policy: always  
    ports:
      - "7860:7860"
# ... existing code ...
```
