### ISSUE TITLE
Tools > MCP Server cannot use Global variable for SSE server

### ISSUE THREAD

**Issue by andrewkcarter** [langflow-ai/langflow#7431]
### Bug Description

**Release 1.3.1**

When using the MCP Server component, it is unable to correctly operate if the SSE server URL is provided through a global variable. Manually typing a URL does work.

### Reproduction

1. Define a global variable that contains the MCP server URL. I'm doing it through ENV on a Helm deployment, but even creating the var manually from the settings page fails.
```
        env: 
...
          - name: LANGFLOW_VARIABLES_TO_GET_FROM_ENVIRONMENT
            value: "TEST_MCP_SSE"
          - name: TEST_MCP_SSE
            value: "http://host.docker.internal:8080/sse"
```
2. Drag an MCP Server onto the canvas.
3. Select SSE and select the global var to use as the URL.
4. Test the component and it fails.
```
[04/03/25 18:31:18] ERROR    2025-04-03 18:31:18 - ERROR    -       <string>:374
                             <string> - Invalid SSE URL
                             configuration: TEST_MCP_SSE. Please
                             check the SSE URL and try again.
```
The component looks ok, but the tools are not loaded and listed.

<img width="293" alt="Image" src="https://github.com/user-attachments/assets/47a07c41-d111-4fe0-8cde-d847493e182b" />

5. Change the URL field from a global var reference to the literal value you set in the global var
6. Test the component and it works.

<img width="283" alt="Image" src="https://github.com/user-attachments/assets/1ec9098b-ea8d-49c1-a83a-637dab9d284e" />

### Expected behavior

The SSE server field should be assignable from a global variable, that is provided through an ENV. This is how we plan to transition flows between development and production systems.

### Who can help?

@ogabrielluiz 

### Operating System

Docker langflowai/langflow:1.3.1

### Langflow Version

1.3.1

### Python Version

3.12
