### ISSUE TITLE
Docker compose issue: Permission denied: '/app/langflow/secret_key'

### ISSUE THREAD

**Issue by shkarupa-alex** [langflow-ai/langflow#7683]
### Bug Description

When running `langflowai/langflow:1.3.3` in produciton server under docker compose, got error:
`PermissionError: [Errno 13] Permission denied: '/app/langflow/secret_key'`

While container was running i was able ru check directory permissions with `ls -la`:
```bash
drwxr-xr-x. 1 user 1000 4096 Apr 17 09:44 .
drwxr-xr-x. 1 root root 4096 Apr 17 09:43 ..
drwxr-xr-x. 7 user 1000 4096 Apr 15 01:09 .venv
drwxr-xr-x. 3 user root 4096 Apr 17 09:44 data
drwxr-xr-x. 2 root root 4096 Apr 17 09:43 langflow
```
The confusing part is why `langflow` directory owned by root if CMD in langflow dockerfile follow after `USER user`

There is not such bug when running same compose on local machine.

### Reproduction

Compose file:
```yaml
services:
  flow:
    image: langflowai/langflow:1.3.3
    volumes:
      - data_flow:/app/langflow
    environment:
      - LANGFLOW_AUTO_LOGIN=False
      - LANGFLOW_SUPERUSER=${FLOW_USER}
      - LANGFLOW_SUPERUSER_PASSWORD=${FLOW_PASSWORD}
      - LANGFLOW_SECRET_KEY=${FLOW_SECRET}
      - LANGFLOW_NEW_USER_IS_ACTIVE=${FLOW_SIGNUP}
      - LANGFLOW_DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
      - LANGFLOW_CONFIG_DIR=/app/langflow
    healthcheck:
      test: "bash -c ':> /dev/tcp/localhost/7860' || exit 1"
      interval: 5s
      timeout: 4s
      retries: 10
    restart: always
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: postgres:13.18-alpine3.20
    hostname: db
    shm_size: 128mb
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always
    healthcheck:
      test: "pg_isready -U ${DB_USER} -d ${DB_NAME} || exit 1"
      interval: 5s
      timeout: 4s
      retries: 10
```

### Expected behavior

No permission error in docker

### Who can help?

@italojohnny 

### Operating System

CentOS Stream 8 + Docker

### Langflow Version

1.3.3

### Python Version

None

**Comment by mimartin12** [comment]
I am getting the same!

**Comment by zkLyons** [comment]
I also encountered the "permission denied" error while running in a Windows environment. The specific error was:
`PermissionError: [Errno 13] Permission denied: 'D:\\A_deep_learning\\langflow\\langflow_cache\\secret_key'`


I tried granting the `secret_key` file full control permissions and also attempted to change the default cache file location, but neither worked. Later, I discovered that I couldn’t manually delete the `secret_key` file, nor did I have permission to open it with Notepad.

By running
`icacls "C:\Users\me\AppData\Local\langflow\langflow\Cache\secret_key"`

I confirmed that I was indeed an administrator. However, the ACL entries of the file were corrupted or missing (invalid SID + insufficient permissions). As a result, even as an administrator, Windows still refused access. The solution was to reset permissions using `takeown` and `icacls`:

1. Change file owner:

`
takeown /f "C:\Users\me\AppData\Local\langflow\langflow\Cache\secret_key"
`

2. Grant full control to the current user:

`
icacls "C:\Users\zkLyons\AppData\Local\langflow\langflow\Cache\secret_key" /grant "${env:USERNAME}:(F)"
`

In the end, this method solved the issue for me. Hope it helps you too.

**Comment by Yahya-khodr** [comment]
in the main service in docker compose file `langflow` changing the volumes to this it worked for me 
```
    volumes:
      # mount to a neutral path (avoid naming collisions with /app/langflow)
      - ./config:/app/config
```

**Comment by Kickbut101** [comment]
I have mine working by adjusting the volume for the langflow service from /app/langflow to /app

```
services:
  langflow:
    image: langflowai/langflow:latest # or another version tag on https://hub.docker.com/r/langflowai/langflow
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - langflow-data:/app
```
