### ISSUE TITLE
Crash when restart the langflow with loading flows from files

### ISSUE THREAD

**Issue by knew-cht** [langflow-ai/langflow#8364]
### Bug Description

I set `LANGFLOW_LOAD_FLOWS_PATH` to load flows from startup Langflow using docker-compose and Langflow startup normally.

However, if I restart the Langflow using `docker compose down` and `docker compose up`, it will get into crash.

The log shows `Application startup failed. Exiting.` with error message `sqlalchemy.exc.StatementError: (builtins.AttributeError) 'str' object has no attribute 'hex'`

And when I remove the flow files in `LANGFLOW_LOAD_FLOWS_PATH` and restart Langflow, it can start up normally.

### Reproduction

1. Set up `LANGFLOW_LOAD_FLOWS_PATH`
2. Add a flow's json file to the path
3. mount the path to `docker-compose.yaml`
4. start Langflow using `docker compose up`
5. check the flow is loaded into langflow
6. stop Langflow using `docker compose down`
7. start Langflow using `docker compose up`

the example of  `docker-compose.yaml`
```yaml
services:
    langflow:
      image: langflowai/langflow:1.4.2
      ports:
        - "7860:7860"
      environment:
        - DO_NOT_TRACK=true
        - LANGFLOW_CONFIG_DIR=/app/langflow
        - LANGFLOW_SAVE_DB_IN_CONFIG_DIR=true
        - LANGFLOW_STORE=false
        - LANGFLOW_LOAD_FLOWS_PATH=/app/langflow/flows
      volumes:
        - ./data:/app/langflow
   ```

### Expected behavior

LangFlow should start normally and ignore the flow which been loaded before or move the files of loaded flows to other place.

### Who can help?

@italojohnny

### Operating System

Ubuntu 24.04.01

### Langflow Version

1.4.2

### Python Version

None
