### ISSUE TITLE
Langflow does not work with redis

### ISSUE THREAD

**Issue by diegobernagozzi** [langflow-ai/langflow#8535]
### Bug Description

Hi everyone,

I'm currently testing the horizontal scalability of Langflow.
I've set up a Docker Compose environment with 4 Langflow backend containers, 1 PostgreSQL container, 1 Redis container, and 1 Nginx container for load balancing.

When I run a flow via the Langflow API, I encounter the following error:

```
TypeError: cannot pickle                           
 'ConsoleThreadLocals' object                       
```

To debug this, I reduced my flow to just two nodes — a Text Input node and a Text Output node — and in that case, everything works fine. However, as soon as I add a single LLM node (e.g., an Ollama node), the error appears again.

Interestingly, the API call still returns a 200 status code, but this error seems to be the main cause of the reduced performance when simulating multiple users.

If I remove Redis from the setup, the error doesn't occur — but I want to use Redis to avoid potential deadlock issues.

### Reproduction

this is my docker compose file

```
services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    command: postgres -c 'max_connections=1000'
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data
    networks:
      - loadbalancing

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis
    volumes:
      - langflow-redis:/data
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    networks:
      - loadbalancing

  langflow-1:
    image: langflowai/langflow-backend:latest # or another version tag on https://hub.docker.com/r/langflowai/langflow
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: always           # set to 'always' when using 'latest' image
    depends_on:
      - postgres
      - redis
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      - LANGFLOW_CONFIG_DIR=app/langflow
      - LANGFLOW_CACHE_TYPE=redis
      - LANGFLOW_REDIS_HOST=redis
      - LANGFLOW_REDIS_PORT=6379
      - LANGFLOW_EVENT_DELIVERY=direct
    volumes:
      - langflow-data:/app/langflow
    networks:
      - loadbalancing
  
  langflow-2:
    image: langflowai/langflow-backend:latest # or another version tag on https://hub.docker.com/r/langflowai/langflow
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: always           # set to 'always' when using 'latest' image
    depends_on:
      - postgres
      - redis
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      - LANGFLOW_CONFIG_DIR=app/langflow
      - LANGFLOW_CACHE_TYPE=redis
      - LANGFLOW_REDIS_HOST=redis
      - LANGFLOW_REDIS_PORT=6379
      - LANGFLOW_EVENT_DELIVERY=direct
    volumes:
      - langflow-data:/app/langflow
    networks:
      - loadbalancing

  langflow-3:
    image: langflowai/langflow-backend:latest # or another version tag on https://hub.docker.com/r/langflowai/langflow
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: always           # set to 'always' when using 'latest' image
    depends_on:
      - postgres
      - redis 
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      - LANGFLOW_CONFIG_DIR=app/langflow
      - LANGFLOW_CACHE_TYPE=redis
      - LANGFLOW_REDIS_HOST=redis
      - LANGFLOW_REDIS_PORT=6379
      - LANGFLOW_EVENT_DELIVERY=direct
    volumes:
      - langflow-data:/app/langflow
    networks:
      - loadbalancing

  langflow-4:
    image: langflowai/langflow-backend:latest # or another version tag on https://hub.docker.com/r/langflowai/langflow
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: always           # set to 'always' when using 'latest' image
    depends_on:
      - postgres
      - redis 
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      - LANGFLOW_CONFIG_DIR=app/langflow
      - LANGFLOW_CACHE_TYPE=redis
      - LANGFLOW_REDIS_HOST=redis
      - LANGFLOW_REDIS_PORT=6379
      - LANGFLOW_EVENT_DELIVERY=direct
    volumes:
      - langflow-data:/app/langflow
    networks:
      - loadbalancing
  
  langflow-5:
    image: langflowai/langflow:latest # or another version tag on https://hub.docker.com/r/langflowai/langflow
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    depends_on:
      - postgres
      - redis # Aggiungi la dipendenza da Redis
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      - LANGFLOW_CONFIG_DIR=app/langflow
      - LANGFLOW_CACHE_TYPE=redis
      - LANGFLOW_REDIS_HOST=redis
      - LANGFLOW_REDIS_PORT=6379
      - LANGFLOW_REDIS_DB=0
      - LANGFLOW_REDIS_PASSWORD=redis
    volumes:
      - langflow-data:/app/langflow
    networks:
      - loadbalancing

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    volumes:
      - ollama_volume:/root/.ollama
  
  nginx:
    build: ../nginx
    ports:
      - "80:80"
    networks:
      - loadbalancing
    depends_on:
      - langflow-1 
  
networks:
  loadbalancing:

volumes:
  langflow-postgres:
  langflow-data:
  langflow-redis: 
  ollama_volume:
```

this is the langflow dockerfile

```
FROM langflowai/langflow-backend:latest
RUN mkdir -p /app/flows
COPY ./*json /app/flows/.
ENV LANGFLOW_LOAD_FLOWS_PATH=/app/flows
```

### Expected behavior

don't get this error

```
TypeError: cannot pickle                           
 'ConsoleThreadLocals' object       
```

### Who can help?

@ogabrielluiz @nicoloboschi @zzzming 

### Operating System

ubuntu 22.04

### Langflow Version

latest

### Python Version

3.12
